pluginGroup=io.github.suhli.datagrip.elasticsearch
pluginName=es-rest-data-source
pluginVersion=0.1.0
pluginSinceBuild=251
platformType=IU
platformVersion=2025.1.4
gradleVersion=8.13
esSpecCommit=9665eef0d78c41f20c4c83e69b7c8155efd58f24
esSpecSha256=370859C2AF07C60EAC724B35AA29ECB70A686F17E6C9052BC1B26FB83F8D0045
esSpecUrl=https://raw.githubusercontent.com/elastic/elasticsearch-specification/9665eef0d78c41f20c4c83e69b7c8155efd58f24/output/schema/schema.json
org.gradle.jvmargs=-Xmx4096m
org.gradle.configuration-cache=true
