import java.net.URI
import java.net.URLConnection
import java.security.MessageDigest

plugins {
    `java-library`
    application
}

java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(21))
    }
}

tasks.withType<JavaCompile>().configureEach {
    options.release.set(17)
    options.encoding = "UTF-8"
}

dependencies {
    implementation("com.fasterxml.jackson.core:jackson-databind:2.22.2")

    testImplementation(platform("org.junit:junit-bom:5.13.4"))
    testImplementation("org.junit.jupiter:junit-jupiter")
    testRuntimeOnly("org.junit.platform:junit-platform-launcher")
}

tasks.test {
    useJUnitPlatform()
}

application {
    mainClass.set("io.github.suhli.datagrip.elasticsearch.codegen.CompletionGeneratorMain")
}

val esSpecCommit: String = providers.gradleProperty("esSpecCommit").orElse(
    "9665eef0d78c41f20c4c83e69b7c8155efd58f24"
).get()
val esSpecSha256: String = providers.gradleProperty("esSpecSha256").orElse("").get()
val esSpecUrl: String = providers.gradleProperty("esSpecUrl").orElse(
    "https://raw.githubusercontent.com/elastic/elasticsearch-specification/$esSpecCommit/output/schema/schema.json"
).get()

val schemaDir = layout.buildDirectory.dir("es-spec")
val schemaFile = schemaDir.map { it.file("schema.json") }
val generatedResources = layout.buildDirectory.dir("generated/completion")

val downloadEsSpec by tasks.registering {
    group = "codegen"
    description = "Download pinned Elasticsearch API specification schema.json"
    inputs.property("esSpecUrl", esSpecUrl)
    inputs.property("esSpecSha256", esSpecSha256)
    outputs.file(schemaFile)
    doLast {
        val target = schemaFile.get().asFile
        target.parentFile.mkdirs()
        // Prefer a pre-seeded local copy to keep CI/dev builds resilient.
        val seeded = rootProject.layout.projectDirectory.file(
            "completion-codegen/build/tmp/schema.json"
        ).asFile
        if (seeded.isFile && seeded.length() > 1_000_000L) {
            seeded.copyTo(target, overwrite = true)
        } else {
            val connection = URI(esSpecUrl).toURL().openConnection() as URLConnection
            connection.connectTimeout = 60_000
            connection.readTimeout = 180_000
            connection.getInputStream().use { input ->
                target.outputStream().use { output -> input.copyTo(output) }
            }
        }
        if (esSpecSha256.isNotBlank()) {
            val digest = MessageDigest.getInstance("SHA-256")
            val hash = digest.digest(target.readBytes()).joinToString("") { b -> "%02x".format(b) }
            if (!hash.equals(esSpecSha256, ignoreCase = true)) {
                throw GradleException(
                    "Elasticsearch specification checksum mismatch. expected=$esSpecSha256 actual=$hash"
                )
            }
        }
    }
}

val generateCompletionResources by tasks.registering(JavaExec::class) {
    group = "codegen"
    description = "Generate es-api-completion.json and es-dsl-completion.json"
    dependsOn(downloadEsSpec, tasks.named("classes"))
    classpath = sourceSets.main.get().runtimeClasspath
    mainClass.set("io.github.suhli.datagrip.elasticsearch.codegen.CompletionGeneratorMain")
    val schema = schemaFile
    val output = generatedResources
    inputs.file(schema)
    inputs.files(sourceSets.main.get().runtimeClasspath)
    outputs.dir(output)
    args(
        schema.map { it.asFile.absolutePath }.get(),
        output.map { it.asFile.absolutePath }.get(),
        esSpecCommit,
    )
    doFirst {
        output.get().asFile.mkdirs()
    }
}

val generated by configurations.creating {
    isCanBeConsumed = true
    isCanBeResolved = false
}

artifacts {
    add(generated.name, generatedResources) {
        builtBy(generateCompletionResources)
    }
}
